-- Add UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "dblink";

SET TIMEZONE = 'Asia/Jakarta';

DO 
$$
    BEGIN
        CREATE TYPE users_status as ENUM ('ACTIVE', 'INACTIVE', 'DISABLED');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

DO
$$
    BEGIN
        CREATE TYPE post_status as ENUM ('PUBLISH', 'DRAFT', 'REVISION', 'ARCHIVED', 'PRIVATE', 'UNPUBLISH');
    EXCEPTION
        WHEN duplicate_object THEN null;
    END
$$;

------------ CREATE TABLE
-- TABLE USERS
CREATE TABLE users
(
    id                  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID DEFAULT uuid_generate_v4(),
    first_name          VARCHAR(100)    NOT NULL,
    last_name           VARCHAR(255)    DEFAULT NULL,
    email               VARCHAR(255)    NOT NULL UNIQUE,
    email_verified_at   TIMESTAMP       NULL,
    password            VARCHAR(255)    NOT NULL,
    remember_token      VARCHAR(255)    NULL,
    status              users_status    NOT NULL DEFAULT 'INACTIVE',
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at          TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_email_not_deleted ON users(email) WHERE deleted_at IS NULL;



-- TABLE ROLES
CREATE TABLE roles
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255)    NOT NULL,
    slug                VARCHAR(255)    NOT NULL,
    description         VARCHAR(255)    DEFAULT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at          TIMESTAMP WITH TIME ZONE DEFAULT NULL 
);

-- TABLE ROLE_USER
CREATE TABLE role_users
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id             INT NOT NULL,
    user_id             INT NOT NULL,
    constraint role_users_role_id_fk FOREIGN KEY (role_id)
               REFERENCES roles(id)
               ON DELETE CASCADE,
    constraint role_users_user_id_fk FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

-- TABLE PERMISSIONS
CREATE TABLE PERMISSIONS
(
    id                  INT GENERATED BY DEFAULT AS IDENTITY primary key,
    name                VARCHAR(255) NOT NULL,
    slug                VARCHAR(255) NOT NULL,
    description         VARCHAR(255) NULL,
    model               VARCHAR(255) NULL,
    created_at          TIMESTAMP DEFAULT NOW(),
    deleted_at          TIMESTAMP DEFAULT NULL,
    updated_at          TIMESTAMP DEFAULT NULL,
    CONSTRAINT permissions_slug_unique
        UNIQUE (slug)
);