DO
$$
BEGIN
CREATE TYPE media_type AS ENUM ('profile', 'template', 'design', 'invitation', 'invoice','invitation_image', 'featured_image');
EXCEPTION
        WHEN duplicate_object THEN null;
END
$$;

create table medias
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename   varchar(255) NOT NULL,
    mime_type  varchar(255) null,
    ext        varchar(20)  null,
    storage    varchar(20)  null,
    type    media_type DEFAULT null,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);